### ISSUE TITLE
error in reference genome sequencing

### ISSUE THREAD

**Issue by SOLBIKWEON** [nadavbra/geneffect#1]
I want to running geneffect but error occurred like this.
I was download reference genome sequencing in ftp://hgdownload.cse.ucsc.edu/goldenPath/hg38/chromosomes/.

but `geneffect_setup = geneffect.Setup('GRCh38')` is not work.
It progressed even in the state of "*.fa.gz", and progressed in the state of decompression "*.fa", but the same error appears.
```
>>> geneffect_setup = geneffect.Setup('GRCh38')
GENEFFECT|PID-22307 [2019-10-23 10:04:06.330873]: Working with reference genome version GRCh38 (user specified: GRCh38).
GENEFFECT|PID-22307 [2019-10-23 10:04:07.111200]: Loaded 93748 pfam records, 51710 of which are domains. Found 347 unique clans within these domains, 173 of which are common (with at least 25 occurrences).
GENEFFECT|PID-22307 [2019-10-23 10:05:11.943933]: Parsed 20365 UniProt records.
GENEFFECT|PID-22307 [2019-10-23 10:05:34.529086]: Loaded 2604486 gene annotations.
GENEFFECT|PID-22307 [2019-10-23 10:05:35.062351]: Loaded 20330 gene meta data records.
GENEFFECT|PID-22307 [2019-10-23 10:05:36.408377]: Constructed 708226 CDS records.
/usr/local/lib/python2.7/dist-packages/Bio/Seq.py:2748: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/geneffect/setup.py", line 23, in __init__
    self.genes = load_genes(self._config_setup, self.genome_reader, self.uniprot_records)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 90, in load_genes
    append_if_not_none(genes, _parse_gene(uniprot_records[uniprot_id], uniprot_cds_rows, genome_reader))
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 98, in _parse_gene
    cds_rows.groupby('transcript_id')]
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 118, in _parse_cds_isoform
    return CDSIsoform(transcript_id, chromosome, strand, cds_coordinates, genome_reader)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 40, in __init__
    self._set_cds_exons(cds_chromosomal_coordinates, genome_reader)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 57, in _set_cds_exons
    cds_exon = CDSExon(self.chromosome, self.strand, chromosome_start, chromosome_end, last_isoform_end + 1, genome_reader)
  File "/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.py", line 77, in __init__
    self.seq = self.positive_strand_seq if strand == '+' else self.positive_strand_seq.reverse_complement()
  File "/usr/local/lib/python2.7/dist-packages/Bio/Seq.py", line 1008, in reverse_complement
    return self.complement()[::-1]
  File "/usr/local/lib/python2.7/dist-packages/Bio/Seq.py", line 966, in complement
    raise ValueError("Mixed RNA/DNA found")
ValueError: Mixed RNA/DNA found
```
How should I resolve this error?

**Comment by nadavbra** [comment]
To help diagnose the problem, I'd ask you to:
1. Send the content of your geneffect configuration file (should be at .~/.geneffect_config.py)
2. List the content of the GRCh38 reference genome directory you set in the config (it should contain an .fa file for each chromosome)
3. To detect the particular gene exon that is failing (and its location on the GRCh38 genome), please run the attached prognosis code and send its output:
[geneffect_prognosis.py.txt](https://github.com/nadavbra/geneffect/files/3768182/geneffect_prognosis.py.txt)

**Comment by SOLBIKWEON** [comment]
1. I attach my geneffect_config.py file in mail.
2. I attach excel file of List the content of the GRCh38 reference genome
directory.
3. Im not detect the particular gene exon.

thank you
solbi

**Comment by nadavbra** [comment]
Hi Solbi,

I did not get the config and Excel files.

About (3), just run the Python code I attached to my previous message and send me the output you get on the screen.

Nadav

**Comment by SOLBIKWEON** [comment]
this is error message about (3), just run in Python.
`GENEFFECT|PID-14966 [2019-10-27 14:16:35.728466]: Working with reference genome version GRCh38 (user specified: GRCh38).GENEFFECT|PID-14966 [2019-10-27 14:16:36.451684]: Loaded 93748 pfam records, 51710 of which are domains. Found 347 unique clans within these domains, 173 of which are common (with at least 25 occurrences).GENEFFECT|PID-14966 [2019-10-27 14:17:45.014952]: Parsed 20365 UniProt records.GENEFFECT|PID-14966 [2019-10-27 14:18:07.502886]: Loaded 2604486 gene annotations.GENEFFECT|PID-14966 [2019-10-27 14:18:08.028657]: Loaded 20330 gene meta data records.GENEFFECT|PID-14966 [2019-10-27 14:18:09.373120]: Constructed 708226 CDS records.---------------------------------------------------------------------------ValueError Traceback (most recent call last)<ipython-input-2-57081a2212d6> in <module>() 31 geneffect.gene_data_loader.CDSExon = CDSExon 32 ---> 33 geneffect_setup = geneffect.Setup('GRCh38')/usr/local/lib/python2.7/dist-packages/geneffect/setup.pyc in __init__(self, user_specified_ref_genome, should_load_pfam_data) 21 22 self.uniprot_records = load_uniprot_data(self._config_setup, self.pfam_data)---> 23 self.genes = load_genes(self._config_setup, self.genome_reader, self.uniprot_records) 24 self.variant_interpreter = VariantInterpreter(self.genome_reader, self.genes) 25 /usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.pyc in load_genes(config_setup, genome_reader, uniprot_records) 88 for uniprot_id, uniprot_cds_rows in cds_records.groupby('uniprot_id'): 89 if uniprot_id in uniprot_records:---> 90 append_if_not_none(genes, _parse_gene(uniprot_records[uniprot_id], uniprot_cds_rows, genome_reader)) 91 92 log('Parsed %d genes.' % len(genes))/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.pyc in _parse_gene(uniprot_record, cds_rows, genome_reader) 96 97 cds_isoforms = [_parse_cds_isoform(transcript_id, transcript_cds_rows, genome_reader) for transcript_id, transcript_cds_rows in \---> 98 cds_rows.groupby('transcript_id')] 99 matching_cds_isoforms = [isoform for isoform in cds_isoforms if isoform.translated_seq == uniprot_record.seq] 100 /usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.pyc in _parse_cds_isoform(transcript_id, transcript_cds_rows, genome_reader) 116 strand, = transcript_cds_rows['strand'].unique() 117 cds_coordinates = [(row['start'], row['end']) for _, row in transcript_cds_rows.iterrows()]--> 118 return CDSIsoform(transcript_id, chromosome, strand, cds_coordinates, genome_reader) 119 120 def _load_cds_records(config_setup):/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.pyc in __init__(self, transcript_id, chromosome, strand, cds_chromosomal_coordinates, genome_reader) 38 self.strand = strand 39 self.codon_table = 'Vertebrate Mitochondrial' if self.chromosome == 'M' else 'Standard'---> 40 self._set_cds_exons(cds_chromosomal_coordinates, genome_reader) 41 self.dna_seq = as_biopython_seq(''.join([str(cds_exon.seq) for cds_exon in self.cds_exons])) 42 self.translated_seq = self.dna_seq.translate(table = self.codon_table)/usr/local/lib/python2.7/dist-packages/geneffect/gene_data_loader.pyc in _set_cds_exons(self, cds_chromosomal_coordinates, genome_reader) 55 56 for chromosome_start, chromosome_end in cds_chromosomal_coordinates:---> 57 cds_exon = CDSExon(self.chromosome, self.strand, chromosome_start, chromosome_end, last_isoform_end + 1, genome_reader) 58 self.cds_exons.append(cds_exon) 59 last_isoform_end = cds_exon.isoform_end<ipython-input-2-57081a2212d6> in __init__(self, chromosome, strand, chromosome_start, chromosome_end, isoform_start, genome_reader) 21 22 self.positive_strand_seq = genome_reader.read_seq(chromosome, chromosome_start, chromosome_end)---> 23 self.seq = self.positive_strand_seq if strand == '+' else self.positive_strand_seq.reverse_complement() 24 except: 25 type, value, traceback = sys.exc_info()/usr/local/lib/python2.7/dist-packages/Bio/Seq.pyc in reverse_complement(self) 1006 """ 1007 # Use -1 stride/step to reverse the complement-> 1008 return self.complement()[::-1] 1009 1010 def transcribe(self):/usr/local/lib/python2.7/dist-packages/Bio/Seq.pyc in complement(self) 964 and ("T" in self._data or "t" in self._data): 965 # TODO - Handle this cleanly?--> 966 raise ValueError("Mixed RNA/DNA found") 967 elif "U" in self._data or "u" in self._data: 968 ttable = _rna_complement_tableValueError: ('Error constructing CDSExon.', <type 'exceptions.ValueError'>, ValueError('Mixed RNA/DNA found',), {'self': CDS Exon 44-354 at chr7:38362864-38363174 (-), 'traceback': <traceback object at 0x7f16c2eddb00>, 'value': ValueError('Mixed RNA/DNA found',), 'isoform_start': 44, 'genome_reader': <geneffect.reference_genome.GenomeReader object at 0x7f16d6f3c090>, 'chromosome_end': 38363174, 'chromosome': '7', 'chromosome_start': 38362864, 'type': <type 'exceptions.ValueError'>, 'strand': '-'})`

and geneffect_config.py file , excel file of List the content of the GRCh38 reference genome directory.
[geneffect_config.txt](https://github.com/nadavbra/geneffect/files/3775722/geneffect_config.txt)
[human_reference_genome_hg38.xlsx](https://github.com/nadavbra/geneffect/files/3775719/human_reference_genome_hg38.xlsx)

**Comment by nadavbra** [comment]
I see you closed the issue.
Is the problem solved?

**Comment by nadavbra** [comment]
Anyway, by looking at your directory of the reference genome, it appears that the problem is that this directory contains the wrong files. It should contain the raw fasta files (.fa), not gzipped files (.fa.gz) - so you need to open the gzip compression. Also make sure that it doesn't contain any other files.

It should contain only these files:

```
chr10.fa
chr11.fa
chr12.fa
chr13.fa
chr14.fa
chr15.fa
chr16.fa
chr17.fa
chr18.fa
chr19.fa
chr1.fa
chr20.fa
chr21.fa
chr22.fa
chr2.fa
chr3.fa
chr4.fa
chr5.fa
chr6.fa
chr7.fa
chr8.fa
chr9.fa
chrM.fa
chrX.fa
chrY.fa
```

**Comment by SOLBIKWEON** [comment]
geneffect is runing
thank you

solbi
